FROM nginx:latest

RUN apt-get update && apt-get install -y \
    gcc \
    libfcgi-dev \
    spawn-fcgi \
    nginx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY server.c /app/server.c
COPY nginx/nginx.conf /etc/nginx/nginx.conf

RUN gcc /app/server.c -o /app/hello -lfcgi

EXPOSE 80

CMD spawn-fcgi -p 8080 /app/hello && nginx -g 'daemon off;'

